data_path:
#  train_data_path: "dataset/train"
  test_data_path: "dataset/test"

image:
  height: 224
  width: 224
  vis_img_save_path: "output/imgs/"


node:
  image_nums: 10
  sampling_interval: 50

graph:
  node_nums: 10
  img_save_path: "output/graph/"